# -*- coding: utf-8 -*-

"""
    Notion API

    Hello and welcome!  To make use of this API collection collection as it's written, please duplicate [this database template](https://www.notion.so/8e2c2b769e1d47d287b9ed3035d607ae?v=dc1b92875fb94f10834ba8d36549bd2a).  [Create an integration](https://www.notion.so/my-integrations) to retrieve an API token, add your database and page ID's as variables in the collection, and start making your requests!  For our full documentation, including sample integrations and guides, visit [developers.notion.com](developers.notion.com)  Need more help? Join our [developer community on Slack](https://join.slack.com/t/notiondevs/shared_invite/zt-lkrnk74h-YmPRroySRFGiqgjI193AqA/)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = 'notion-client'
VERSION = '1.0.0'
PYTHON_REQUIRES = '>=3.7'
REQUIRES = [
    'urllib3 >= 1.25.3',
    'python-dateutil',
    'pydantic',
    'aenum'
]

setup(
    name=NAME,
    version=VERSION,
    description='Notion API',
    author='OpenAPI Generator community',
    author_email='team@openapitools.org',
    url='',
    keywords=['OpenAPI', 'OpenAPI-Generator', 'Notion API'],
    install_requires=REQUIRES,
    packages=find_packages(exclude=['test', 'tests']),
    include_package_data=True,
    long_description_content_type='text/markdown',
    long_description="""\
    Hello and welcome!  To make use of this API collection collection as it&#39;s written, please duplicate [this database template](https://www.notion.so/8e2c2b769e1d47d287b9ed3035d607ae?v&#x3D;dc1b92875fb94f10834ba8d36549bd2a).  [Create an integration](https://www.notion.so/my-integrations) to retrieve an API token, add your database and page ID&#39;s as variables in the collection, and start making your requests!  For our full documentation, including sample integrations and guides, visit [developers.notion.com](developers.notion.com)  Need more help? Join our [developer community on Slack](https://join.slack.com/t/notiondevs/shared_invite/zt-lkrnk74h-YmPRroySRFGiqgjI193AqA/)  # noqa: E501
    """
)
